# HelixHive Genome
# Phase 1 Refactored – with constitution and model proposal defaults

tick: 0
consecutive_failures: 0

helicity:
  current_phase: 0
  flip_interval: 50
  last_flip_tick: 0
  mutation_bias: 0.05
  invariance_tolerance: 0.1

council:
  weights:
    guardian: 2
    visionary: 1.5
    # others default to 1

ethics:
  forbidden_patterns:
    - "hate speech"
    - "illegal"

constitution:
  protected:
    - "ethics.forbidden_patterns"
    - "council.weights.guardian"
    - "constitution.protected"
  amend_threshold: 5/6
  supermajority: 0.833

evo2:
  enabled: true
  fitness_weights:
    e8_consistency: 0.3
    leech_similarity: 0.4
    novelty_bonus: 0.2
    phase_alignment: 0.1
  temperature: 0.8
  max_tokens: 1000

pipeline:
  enabled: true
  refinement_rounds: 3
  max_product_words: 1500

immune:
  failure_threshold: 5
  anomaly_threshold: 2.0
  healing_cooldown: 3600
  max_per_heartbeat: 3

market:
  min_reputation: 10
  auction_duration: 3600
  max_listings_per_agent: 5

revelation:
  enabled: true
  generate_interval: 10

model_proposals:
  min_validation_score: 0.7
  spawn_repo: true
  template_repo: "helixhive-template"

# GitHub App settings (to be overridden by environment or config)
github_app_id: ""
github_private_key_path: ""
github_installation_id: ""
template_owner: ""
daughter_owner: "”
